import { ArrowRight, CheckCircle2, Clock3, ExternalLink } from "lucide-react"

export default function HomePage({ runs, liveRuns, health, onNavigate }) {
  const latest = runs?.[0]
  const ready = health?.status === "ok" || health?.status === "healthy" || health?.ready === true
  return <main className="space-y-6" aria-labelledby="home-title">
    <div><p className="text-xs uppercase tracking-widest text-[#92751A]">Operator home</p><h1 id="home-title" className="font-[Playfair_Display] text-[24px] text-abyss-ink">What do you want to do next?</h1></div>
    <div className="grid lg:grid-cols-3 gap-4">
      <section className="bg-white border border-stone-ridge rounded-lg p-5"><h2 className="font-semibold">What’s next</h2><div className="grid gap-2 mt-4"><button type="button" onClick={() => onNavigate("Run Design")} className="text-left rounded border p-3 hover:bg-[#F8FAFC] focus-visible:outline-2 focus-visible:outline-blue-600">Run an example <ArrowRight size={14} className="inline ml-2" /></button><button type="button" onClick={() => onNavigate("Learning Path")} className="text-left rounded border p-3 hover:bg-[#F8FAFC] focus-visible:outline-2 focus-visible:outline-blue-600">Learn the flow <ArrowRight size={14} className="inline ml-2" /></button><button type="button" onClick={() => onNavigate("Compare Runs")} className="text-left rounded border p-3 hover:bg-[#F8FAFC] focus-visible:outline-2 focus-visible:outline-blue-600">Compare results <ArrowRight size={14} className="inline ml-2" /></button></div></section>
      <section className="bg-white border border-stone-ridge rounded-lg p-5"><h2 className="font-semibold">Is my environment ready?</h2><div className="flex items-center gap-3 mt-5"><CheckCircle2 className={ready ? "text-green-600" : "text-amber-600"} aria-hidden="true" /><div><p className="font-medium">{ready ? "Ready" : "Needs attention"}</p><p className="text-xs text-[#52606D]">{health?.message || "Run Doctor for detailed checks."}</p></div></div><button type="button" onClick={() => onNavigate("Infrastructure")} className="mt-5 text-sm underline focus-visible:outline-2 focus-visible:outline-blue-600">Open environment checks</button></section>
      <section className="bg-white border border-stone-ridge rounded-lg p-5"><h2 className="font-semibold">What changed?</h2>{latest ? <div className="mt-4"><p className="text-sm">Latest: <span className="font-medium">{latest.design_name}</span></p><p className="text-xs text-[#52606D] mt-1">{latest.status} · {latest.current_stage}</p><button type="button" onClick={() => onNavigate("Run Monitor")} className="mt-5 text-sm underline focus-visible:outline-2 focus-visible:outline-blue-600">Open last result <ExternalLink size={13} className="inline ml-1" /></button></div> : <div className="mt-4"><p className="text-sm text-[#52606D]">No runs yet.</p><button type="button" onClick={() => onNavigate("Run Design")} className="mt-3 rounded bg-abyss-ink text-white px-3 py-2 text-sm focus-visible:outline-2 focus-visible:outline-blue-600">Run your first example</button></div>}</section>
    </div>
    {liveRuns?.length > 0 && <section className="bg-[#EFF6FF] border border-[#BFDBFE] rounded-lg p-4" aria-live="polite"><div className="flex items-center gap-2 font-medium"><Clock3 size={16} aria-hidden="true" />Active run status</div>{liveRuns.map(run => <p key={run.run_id} className="text-sm mt-2">{run.run_id}: {run.current_stage} · {run.progress ?? 0}% · <button type="button" className="underline focus-visible:outline-2 focus-visible:outline-blue-600" onClick={() => onNavigate("Run Monitor")}>live logs/artifacts</button></p>)}</section>}
  </main>
}
