import { useEffect, useState } from "react"
import { GitCompareArrows, Download } from "lucide-react"

const API_BASE = import.meta.env.VITE_API_URL || ""
const METRICS = ["timing_slack", "area", "power", "utilization", "drc", "runtime"]

export default function RunComparisonPage() {
  const [runs, setRuns] = useState([]); const [selected, setSelected] = useState([]); const [result, setResult] = useState(null); const [threshold, setThreshold] = useState(10); const [error, setError] = useState("")
  useEffect(() => { fetch(`${API_BASE}/runs?limit=100`).then(r => r.json()).then(setRuns).catch(() => setError("Run history is unavailable.")) }, [])
  const toggle = id => setSelected(s => s.includes(id) ? s.filter(x => x !== id) : [...s, id])
  async function compare() { setError(""); const response = await fetch(`${API_BASE}/runs/compare`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ run_ids: selected, thresholds: { timing_slack: threshold } }) }); const data = await response.json(); if (!response.ok) setError(data.detail || "Select at least two runs."); else setResult(data) }
  async function exportAs(format) { const response = await fetch(`${API_BASE}/runs/compare/export`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ run_ids: selected, format }) }); const blob = await response.blob(); if (!response.ok) { setError(await blob.text()); return } const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `gli-flow-comparison.${format === "markdown" ? "md" : format}`; link.click(); URL.revokeObjectURL(url) }
  return <main className="space-y-6" aria-labelledby="comparison-title">
    <div className="flex items-center gap-3"><GitCompareArrows aria-hidden="true" /><div><h1 id="comparison-title" className="font-[Playfair_Display] text-[24px] text-abyss-ink">Compare runs</h1><p className="text-sm text-[#52606D]">Compare compatible evidence and keep simulated data visibly labelled.</p></div></div>
    <section className="bg-white border border-stone-ridge rounded-lg p-5"><h2 className="font-semibold">Choose runs</h2>{runs.length < 2 ? <p className="text-sm text-[#52606D] mt-3">Run this design {2 - runs.length} more time(s) to see trends.</p> : <div className="grid gap-2 mt-3">{runs.map(run => <label key={run.run_id} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={selected.includes(run.run_id)} onChange={() => toggle(run.run_id)} />{run.run_id} · {run.design_name}<span className="text-[10px] text-[#92751A]">{run.is_experiment ? "SIMULATED / EXPERIMENT" : "RUN"}</span></label>)}</div>}<label className="inline-flex items-center gap-2 text-sm mt-4">Timing regression limit (%)<input className="border rounded px-2 py-1 w-20 focus-visible:outline-2 focus-visible:outline-blue-600" type="number" value={threshold} onChange={e => setThreshold(Number(e.target.value))} /></label><div className="flex flex-wrap gap-2 mt-4"><button type="button" onClick={compare} disabled={selected.length < 2} className="rounded bg-abyss-ink text-white px-4 py-2 text-sm disabled:opacity-50 focus-visible:outline-2 focus-visible:outline-blue-600">Compare selected</button>{["csv", "json", "markdown"].map(format => <button type="button" key={format} onClick={() => exportAs(format)} disabled={!result?.compatible} className="inline-flex gap-1 items-center rounded border px-3 py-2 text-sm disabled:opacity-50 focus-visible:outline-2 focus-visible:outline-blue-600"><Download size={13} aria-hidden="true" />{format.toUpperCase()}</button>)}</div>{error && <p role="alert" className="text-sm text-[#991B1B] mt-3">{error}</p>}</section>
    {result?.compatible === false && <p role="alert" className="bg-[#FFF7ED] border border-[#FED7AA] rounded p-4 text-sm text-[#9A3412]">{result.reason} The comparison was refused.</p>}
    {result?.compatible && <section className="bg-white border border-stone-ridge rounded-lg p-5 overflow-x-auto"><h2 className="font-semibold mb-3">Metric comparison</h2><table className="w-full text-sm"><thead><tr><th className="text-left">Run</th>{METRICS.map(metric => <th key={metric} className="text-right px-2">{metric.replace("_", " ")}</th>)}</tr></thead><tbody>{result.runs.map(run => <tr key={run.run_id} className="border-t"><td className="py-2">{run.run_id}<div className="text-[10px] text-[#92751A]">{run.metric_quality}</div></td>{METRICS.map(metric => <td key={metric} className="text-right px-2">{run.values[metric] ?? "—"}</td>)}</tr>)}</tbody></table>{result.regressions?.map(check => <p key={check.metric} className={`text-sm mt-2 ${check.pass ? "text-green-700" : "text-red-700"}`}>{check.pass ? "PASS" : "FAIL"}: {check.message}</p>)}</section>}
  </main>
}
